package com.weatherapp.network.model

data class DayResponse(
    val datetime: String? = null,
    val datetimeEpoch: Long? = null,
    val tempmax: Double? = null,
    val tempmin: Double? = null,
    val temp: Double? = null,
    val feelslikemax: Double? = null,
    val feelslikemin: Double? = null,
    val feelslike: Double? = null,
    val dew: Double? = null,
    val humidity: Double? = null,
    val precip: Double? = null,
    val precipprob: Double? = null,
    val precipcover: Double? = null,
    val preciptype: List<String>? = null,
    val snow: Long? = null,
    val snowdepth: Int? = null,
    val windgust: Double? = null,
    val windspeed: Double? = null,
    val winddir: Double? = null,
    val pressure: Double? = null,
    val cloudcover: Double? = null,
    val visibility: Double? = null,
    val uvindex: Int? = null,
    val sunrise: String? = null,
    val sunriseEpoch: Long? = null,
    val sunset: String? = null,
    val sunsetEpoch: Long? = null,
    val moonphase: Double? = null,
    val conditions: String? = null,
    val description: String? = null,
    val icon: String? = null,
    val source: String? = null,
    val hours: List<DayResponse>? = null,
    val precipsum: Long? = null,
    val precipsumnormal: Long? = null,
    val snowsum: Long? = null,
    val datetimeInstance: String? = null
)