package com.weatherapp.domain.model

data class Day(
    val datetime: String,
    val tempmax: Int?,
    val tempmin: Int?,
    val temp: Int?,
    val feelslikemax: Int?,
    val feelslikemin: Int?,
    val feelslike: Int?,
    val humidity: Double?,
    val precip: Double?,
    val preciptype: List<PrecipationType>?,
    val windspeed: Double?,
    val pressure: Double?,
    val visibility: Double,
    val uvindex: Int?,
    val sunrise: String,
    val sunset: String,
    val conditions: String,
    val description: String,
    val icon: String,
    val source: String,
    val hours: List<Hours>?,
)